if &compatible
    set nocompatible
endif

" dein settings {{{
" dein自体の自動インストール
let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.cache') : $XDG_CACHE_HOME
let s:dein_dir = s:cache_home . '/dein'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repo_dir)
  call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
endif
let &runtimepath = s:dein_repo_dir .",". &runtimepath
" プラグイン読み込み＆キャッシュ作成
let s:toml = fnamemodify(expand('<sfile>'), ':h').'/dein.toml'
let s:lazy_toml = fnamemodify(expand('<sfile>'), ':h').'/dein_lazy.toml'
if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)
  call dein#load_toml(s:toml,      {'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy': 1})
  call dein#end()
  call dein#save_state()
endif
" 不足プラグインの自動インストール
if has('vim_starting') && dein#check_install()
  call dein#install()
endif
" }}} dein settings

"""""""""""""""""""""""""""""""
" insertion-mode, status-bar settings
"""""""""""""""""""""""""""""""
let g:hi_insert = 'highlight StatusLine guifg=darkblue guibg=darkyellow gui=none ctermfg=blue ctermbg=yellow cterm=none'

if has('syntax')
augroup InsertHook
    autocmd!
    autocmd InsertEnter * call s:StatusLine('Enter')
    autocmd InsertLeave * call s:StatusLine('Leave')
augroup END
endif

let s:slhlcmd = ''
function! s:StatusLine(mode)
if a:mode == 'Enter'
    silent! let s:slhlcmd = 'highlight ' . s:GetHighlight('StatusLine')
    silent exec g:hi_insert
else
    highlight clear StatusLine
    silent exec s:slhlcmd
endif
endfunction
function! s:GetHighlight(hi)
redir => hl
exec 'highlight '.a:hi
redir END
let hl = substitute(hl, '[\r\n]', '', 'g')
let hl = substitute(hl, 'xxx', '', '')
return hl
endfunction
""""""""""""""""""""""""""""""

filetype plugin indent on     " required!

syntax on
colorscheme desert
set t_Co=256
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,euc-jp,sjis,cp934,iso-2022-jp
set scrolloff=5
set backspace=indent,eol,start
set vb t_vb=
set nostartofline
set showmatch
set matchtime=3
set wrap
set shiftround
set ignorecase
set smartcase
set mouse=a
if !has('nvim')
    set ttymouse=xterm2
endif
set showcmd
set number
set history=2000
set helplang=en
set laststatus=2
set ruler
set expandtab
set tabstop=4
set autoindent
set pumheight=10
set hlsearch
set shiftwidth=4
set tags=~/.tags
set wildmenu
set incsearch
set background=dark
set whichwrap=b,s,h,l,<,>,[,]
set listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%,eol:↲
set nolist
if has('persistent_undo')
    set undodir="$HOME/.vim/undo"
    set undofile
end

highlight LineNr ctermfg=darkgray

inoremap jj <Esc>
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <C-d> <Delete>
function! ImInActivate()
  call system('fcitx-remote -c')
endfunction
if has('unix')
    inoremap <silent> <C-[> <ESC>:call ImInActivate()<CR>
endif

nnoremap <C-]> g<C-]>
nnoremap Y y$
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz
nnoremap <buffer> <F9> :exec '!python' shellescape(@%, 1)<cr>
nmap <CR> i<CR><ESC>

cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-h> <Backspace>
cnoremap <C-d> <Delete>
cnoremap <C-k> <C-\>e getcmdpos() == 1 ? '' : getcmdline()[:getcmdpos()-2]<CR>

augroup MyXML
  autocmd!
  autocmd Filetype xml inoremap <buffer> </ </<C-x><C-o>
augroup END

source ~/.vim/abbreviate.vim
